//debug a.cpp -o a.exe && ./a.exe</mnt/d/Projects/CPP_Sublime/inputf.in
#include<bits/stdc++.h>
using namespace std;
typedef long long ll;
void solve()
{
	
}
int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	// clock_t z=clock();
	ll tt=1;
	
	cin>>tt;
	while(tt--)
		solve();
	// cerr<<"[Finished in "<<(double)(clock()-z)*1000/(CLOCKS_PER_SEC)<<"ms]\n";
}
/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: $%U%$
 * Time: $%Y%$-$%M%$-$%D%$ $%h%$:$%m%$:$%s%$
**/